title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
theme: jekyll_cmdbrew
plugins:
  - jekyll_cmdbrew
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tagging-related_posts

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post

# Specify sass files paths
sass:
  load_paths:
    - _sass
    - node_modules

# jekyll_cmdbrew
jekyll_cmdbrew:
  logo: https://placeimg.com/284/284/any
  favicon: https://placeimg.com/128/128/any
  date_format: "%b %-d, %Y"
  theme:
    primary: '#FFB2FF'
    secondary: '#6F767E'
    success: '#28A745'
    warning: '#FFC107'
    danger: '#DC3545'
    info: '#17A2B8'
    light: '#6F767E'
    body_color: '#FFFFFF'
    body_bg: '#222426'
    border_color: '#43484C'
    panel_bg: '#343A40'

# Disqus comments
disqus:
  shortname: test-656tth5lxb

# Pagination
paginate: 10

