# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Welcome to enTree
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true # set to true to show excerpts on the homepage
show_drafts: false
timezone: 'Pacific Time (US & Canada)'
google_analytics: null

# Build settings
theme: entree
plugins:
  - entree
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tagging-related_posts

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
      module: pages
      hidden: true
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      module: posts
      hidden: false
      social_feed:
        facebook:
          enabled: true
        twitter:
          enabled: true
          hashtags: true
        linkedin:
          enabled: true
  - scope:
      path: ''
      type: photos
    values:
      layout: photo
      module: photos
      hidden: false

# Specify sass files paths
sass:
  load_paths:
    - _sass
    - node_modules

# entree
entree:
  logo: /assets/img/entree/logo.png
  favicon: /assets/img/entree/favicon.ico
  theme: default/light
  sass:
    custom_vars: null
    custom_styles: null
  snippets:
    footer: null
    header: null
  date_format: "%B %-d, %Y"
  generators:
    pages:
      index:
        layout: pages.html
        dir: pages
      tags:
        layout: pages.html
        dir: pages/tags
      categories:
        layout: pages.html
        dir: pages/categories
    posts:
      index:
        layout: posts.html
        dir: posts
      tags:
        layout: posts.html
        dir: posts/tags
      categories:
        layout: posts.html
        dir: posts/categories
      years:
        layout: posts.html
        dir: posts/years
    photos:
      index:
        layout: photos.html
        dir: photos
      tags:
        layout: photos.html
        dir: photos/tags
      categories:
        layout: photos.html
        dir: photos/categories
      years:
        layout: photos.html
        dir: photos/years

# Collections
collections:
  photos:
    output: true
    sort_by: date

# Disqus comments
disqus:
  shortname: ilung
  enabled: true

# Pagination
paginate: 10

# Exclude when compiling
exclude:
 - config/
 - README.md

# Social Feed
feed:
  excerpt_only: false

social_feeds:
  twitter:
    format: "@title: @url@tags"
    url_length: 22
    max_length: 140