# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CMDBrew Studio Inc
email: dev@cmdbrew.com
author: CMDBrew Studio Inc
description: >- # this means to ignore newlines until "baseurl:"
  We build, manage, mantain, mobile (Android/iOS) and web applications
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true # set to true to show excerpts on the homepage
show_drafts: false

# Build settings
theme: jekyll_cmdbrew
plugins:
  - jekyll_cmdbrew
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tagging-related_posts

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post

# jekyll_cmdbrew
jekyll_cmdbrew:
  date_format: "%b %-d, %Y"
  logo: /assets/img/logo.png
  favicon: /assets/img/favicon.ico
  sass:
    custom_vars: 'custom_vars'
    custom_styles:
      - 'custom_styles'

# Disqus comments
disqus:
  shortname: cmdbrew

# Pagination
paginate: 10

# Social Feed
social_feeds:
  twitter:
    format: "@title: @url@tags"
    url_length: 22
    max_length: 140