title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
theme: jekyll_cmdbrew
plugins:
  - jekyll_cmdbrew
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tagging-related_posts

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  - scope:
      path: ''
      type: files
    values:
      layout: file

# Specify sass files paths
sass:
  load_paths:
    - _sass
    - node_modules

# jekyll_cmdbrew
jekyll_cmdbrew:
  cookies_policy: true
  file_preview_whitelist:
    - jpg
    - jpeg
    - gif
    - png
    - svg
  sass:
    custom_vars: null
    custom_styles: null
  snippets:
    footer: null
    header: null
  logo: https://placeimg.com/284/284/any
  favicon: https://placeimg.com/128/128/any
  date_format: "%b %-d, %Y"

# Collection Directories
post_dir: posts
tag_dir: tags
post_dir: posts
file_dir: files

# Collections
collections:
  files:
    output: true

# Disqus comments
disqus:
  shortname: null

# Pagination
# paginate: 10

# Social Feed
social_feeds:
  twitter:
    format: "@title: @url@tags"
    url_length: 22
    max_length: 140