---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
- type: heading
  label: Contents
- type: jekyll-pages
  label: Pages
  create: documents
  templates:
  - pages
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - posts
- type: directory
  path: _photos
  label: Photos
  create: documents
  match: "**/*"
  templates:
  - photos
- type: heading
  label: Components
- type: document
  path: _data/menus.yml
  label: Menus
- type: document
  path: _data/notices.yml
  label: Notices
- type: heading
  label: Settings
- type: document
  path: _data/locales.yml
  label: Locales
- type: document
  path: _data/configs.yml
  label: General
upload_dir: uploads
public_path: uploads
front_matter_path: ''
use_front_matter_path:
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - BUNDLE_GITHUB__COM=14e32825c3ae89cfc39e9cdd4cd8ad36d925b33f
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
