***REMOVED***
label: Configs
hide_body: true
fields:
- type: field_group
  name: home
  label: Home
  fields:
  - name: tabs
    type: list
    config:
      use_select: true
      min:
      max: '5'
      source:
        type: simple
      options:
    ***REMOVED***
    ***REMOVED***
      - about
      - categories
    ***REMOVED***
    label: Tabs
    description: 'Available options are: posts, files, about, categories, pages'
- type: field_group
  name: files
***REMOVED***
  fields:
  - type: select
    name: display
    label: Default Display
    default: []
    config:
      required: true
      options:
      - list
      - grid
      source:
        type: simple
        section:
        file:
        path:
pages:
- _data/configs.yml
